# myInspiration™
name: Wordpress site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the wordpress/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/wordpress -v ${{ github.workspace }}/_site:/srv/wordpress/_site \
        wordpress/builder:latest /bin/bash -c "chmod -R 777 /srv/wordpress && wordpress build --future"
